"""initial_schema

Revision ID: 4c01bbe5cc6f
Revises: 
Create Date: 2026-02-18 00:31:04.743349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c01bbe5cc6f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('title', sa.String(length=255), nullable=False, comment='Category name'),
    sa.Column('slug', sa.String(length=255), nullable=False, comment='URL-friendly slug'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether category is active'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_categories_is_active'), 'categories', ['is_active'], unique=False)
    op.create_table('images',
    sa.Column('url', sa.String(length=2048), nullable=False, comment='Image URL or storage path'),
    sa.Column('filename', sa.String(length=500), nullable=True, comment='Original filename'),
    sa.Column('content_type', sa.String(length=100), nullable=True, comment='MIME content type (e.g. image/jpeg)'),
    sa.Column('size', sa.Integer(), nullable=True, comment='File size in bytes'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredients',
    sa.Column('title', sa.String(length=255), nullable=False, comment='Ingredient name'),
    sa.Column('unit_of_measurement', sa.String(length=50), nullable=False, comment='Unit of measurement (g, ml, pcs, etc.)'),
    sa.Column('slug', sa.String(length=255), nullable=False, comment='URL-friendly slug'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether ingredient is active'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_ingredients_is_active'), 'ingredients', ['is_active'], unique=False)
    op.create_table('recipes',
    sa.Column('title', sa.String(length=500), nullable=False, comment='Recipe title'),
    sa.Column('photo_url', sa.String(length=2048), nullable=False, comment='Recipe photo URL'),
    sa.Column('description', sa.Text(), nullable=False, comment='Recipe description'),
    sa.Column('protein', sa.Numeric(precision=8, scale=2), nullable=True, comment='Protein per serving (grams)'),
    sa.Column('fat', sa.Numeric(precision=8, scale=2), nullable=True, comment='Fat per serving (grams)'),
    sa.Column('carbs', sa.Numeric(precision=8, scale=2), nullable=True, comment='Carbohydrates per serving (grams)'),
    sa.Column('prep_time', sa.Integer(), nullable=False, comment='Preparation time in minutes'),
    sa.Column('cook_time', sa.Integer(), nullable=False, comment='Cooking time in minutes'),
    sa.Column('difficulty', sa.String(length=10), nullable=False, comment='Difficulty level: easy, medium, hard'),
    sa.Column('servings', sa.String(length=50), nullable=False, comment='Number of servings'),
    sa.Column('slug', sa.String(length=255), nullable=False, comment='URL-friendly slug'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether recipe is active'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("difficulty IN ('easy', 'medium', 'hard')", name='ck_recipes_difficulty'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_recipes_difficulty', 'recipes', ['difficulty'], unique=False)
    op.create_index(op.f('ix_recipes_is_active'), 'recipes', ['is_active'], unique=False)
    op.create_table('users',
    sa.Column('tg_id', sa.BigInteger(), nullable=False, comment='Telegram user ID'),
    sa.Column('tg_username', sa.String(length=255), nullable=True, comment='Telegram username'),
    sa.Column('username', sa.String(length=255), nullable=True, comment='App username'),
    sa.Column('phone_number', sa.String(length=20), nullable=True, comment='Phone number'),
    sa.Column('first_name', sa.String(length=255), nullable=True, comment='First name'),
    sa.Column('last_name', sa.String(length=255), nullable=True, comment='Last name'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_table('admins',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='FK to users.id — one admin record per user'),
    sa.Column('username', sa.String(length=255), nullable=True, comment='Admin login username'),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='Bcrypt password hash'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_admins_user_id', 'admins', ['user_id'], unique=True)
    op.create_table('cooking_history',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User FK'),
    sa.Column('recipe_id', sa.UUID(), nullable=False, comment='Recipe FK'),
    sa.Column('cooked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When the recipe was cooked'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cooking_history_cooked_at', 'cooking_history', ['cooked_at'], unique=False)
    op.create_index('ix_cooking_history_recipe', 'cooking_history', ['recipe_id'], unique=False)
    op.create_index('ix_cooking_history_user', 'cooking_history', ['user_id'], unique=False)
    op.create_table('favorite_recipes',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User FK'),
    sa.Column('recipe_id', sa.UUID(), nullable=False, comment='Recipe FK'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recipe_id', name='uq_user_recipe_favorite')
    )
    op.create_index('ix_favorite_recipes_recipe', 'favorite_recipes', ['recipe_id'], unique=False)
    op.create_index('ix_favorite_recipes_user', 'favorite_recipes', ['user_id'], unique=False)
    op.create_table('recipe_categories',
    sa.Column('recipe_id', sa.UUID(), nullable=False, comment='Recipe FK'),
    sa.Column('category_id', sa.UUID(), nullable=False, comment='Category FK'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id', 'category_id', name='uq_recipe_category')
    )
    op.create_index('ix_recipe_categories_category', 'recipe_categories', ['category_id'], unique=False)
    op.create_index('ix_recipe_categories_recipe', 'recipe_categories', ['recipe_id'], unique=False)
    op.create_table('recipe_ingredients',
    sa.Column('recipe_id', sa.UUID(), nullable=False, comment='Recipe FK'),
    sa.Column('ingredient_id', sa.UUID(), nullable=False, comment='Ingredient FK'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Amount of ingredient'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recipe_ingredients_ingredient', 'recipe_ingredients', ['ingredient_id'], unique=False)
    op.create_index('ix_recipe_ingredients_recipe', 'recipe_ingredients', ['recipe_id'], unique=False)
    op.create_table('steps',
    sa.Column('recipe_id', sa.UUID(), nullable=False, comment='Recipe FK'),
    sa.Column('step_number', sa.Integer(), nullable=False, comment='Step order number'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='Step title'),
    sa.Column('description', sa.Text(), nullable=True, comment='Step description'),
    sa.Column('photo_url', sa.String(length=2048), nullable=True, comment='Step photo URL'),
    sa.Column('slug', sa.String(length=255), nullable=True, comment='URL-friendly slug (optional)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether step is active'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_steps_recipe_number', 'steps', ['recipe_id', 'step_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_steps_recipe_number', table_name='steps')
    op.drop_table('steps')
    op.drop_index('ix_recipe_ingredients_recipe', table_name='recipe_ingredients')
    op.drop_index('ix_recipe_ingredients_ingredient', table_name='recipe_ingredients')
    op.drop_table('recipe_ingredients')
    op.drop_index('ix_recipe_categories_recipe', table_name='recipe_categories')
    op.drop_index('ix_recipe_categories_category', table_name='recipe_categories')
    op.drop_table('recipe_categories')
    op.drop_index('ix_favorite_recipes_user', table_name='favorite_recipes')
    op.drop_index('ix_favorite_recipes_recipe', table_name='favorite_recipes')
    op.drop_table('favorite_recipes')
    op.drop_index('ix_cooking_history_user', table_name='cooking_history')
    op.drop_index('ix_cooking_history_recipe', table_name='cooking_history')
    op.drop_index('ix_cooking_history_cooked_at', table_name='cooking_history')
    op.drop_table('cooking_history')
    op.drop_index('ix_admins_user_id', table_name='admins')
    op.drop_table('admins')
    op.drop_table('users')
    op.drop_index(op.f('ix_recipes_is_active'), table_name='recipes')
    op.drop_index('ix_recipes_difficulty', table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_ingredients_is_active'), table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_table('images')
    op.drop_index(op.f('ix_categories_is_active'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
